version: '3.8'

services:
  app:
    image: hugocadieu/my-app:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    environment:
      DB_HOST: 10.141.113.128
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: test
